### ISSUE TITLE
Inconsistency in temporal model output shapes

### ISSUE THREAD

**Issue by dmitra79** [HazyResearch/flyingsquid#10]
Hello,

I am playing with temporal models, like in Video.ipynb tutorial. One thing I noticed was that for those  models, with v>1, the return shapes are different for `label_model.predict` and  `label_model.predict_proba_marginalized`. The former returns a value for each v in a frame, while the later returns a single value for the whole frame. So if v=3, and there are 1000 frames, the first returns (1000,3) while the second returns (3000,). I think it would be convenient to have the same shapes in both cases. 

Thanks!

**Comment by DanFu09** [comment]
Thanks for this suggestion! The difference between `predict` and `predict_proba_marginalized` is that `predict` operates in terms of "sequences" (for v=3, this would be sequences of 3 frames), while `predict_proba_marginalized` flattens them out into individual elements. That's why `predict` returns (1000, 3), and `predict_proba_marginalized` returns (3000,).
